[book]
title = "InfraStructure Documentation"
author = "Subramani"
description = "The example book covers examples."
language = "en"

[rust]
edition = "2018"

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true
#additional-css = ["custom.css"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
